- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: mongo_schema_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo_schema_setup